export const weatherCode = [
  { key: 0, value: "Clear sky" },
  { key: 1, value: "Mainly clear" },
  { key: 2, value: "Partly cloudy" },
  { key: 3, value: "Overcast" },
  { key: 45, value: "Fog" },
  { key: 48, value: "Depositing rime fog" },
  { key: 51, value: "Drizzle light" },
  { key: 53, value: "Drizzle moderate" },
  { key: 55, value: "Drizzle dense intensity" },
  { key: 56, value: "Freezing drizzle light" },
  { key: 57, value: "Freezing drizzle dense intensity" },
  { key: 61, value: "Rain slight" },
  { key: 63, value: "Rain moderate" },
  { key: 65, value: "Rain heavy intensity" },
  { key: 66, value: "Freezing rain light" },
  { key: 67, value: "Freezing rain heavy intensity" },
  { key: 71, value: "Snow fall slight" },
  { key: 73, value: "Snow fall moderate" },
  { key: 75, value: "Snow fall heavy intensity" },
  { key: 77, value: "Snow grains" },
  { key: 80, value: "Rain showers slight" },
  { key: 81, value: "Rain showers moderate" },
  { key: 82, value: "Rain showers violent" },
  { key: 85, value: "Snow showers slight" },
  { key: 86, value: "Snow showers heavy" },
  { key: 95, value: "Thunderstorm slight" },
  { key: 96, value: "Thunderstorm with slight hail" },
  { key: 99, value: "Thunderstorm with heavy hail" },
];
